######################################################################
#
# File name : anchor_top_tb_wave.do
# Created on: Thu Dec 06 15:02:12 CST 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
