######################################################################
#
# File name : mcu_to_fpga_tb_wave.do
# Created on: Tue Dec 04 09:32:39 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
