######################################################################
#
# File name : mcu_to_fpga_tb_simulate.do
# Created on: Thu Dec 06 11:14:17 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.mcu_to_fpga_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {mcu_to_fpga_tb_wave.do}

view wave
view structure
view signals

do {mcu_to_fpga_tb.udo}

run 1000ns
