######################################################################
#
# File name : mcu_to_fpga_tb_compile.do
# Created on: Mon Dec 03 16:45:03 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../../firmware/fpga/include" \
"../../../../../../firmware/fpga/util/math/xilinx/math_mult_32/math_mult_32_sim_netlist.v" \
"../../../../../../firmware/fpga/xcorr/xilinx/axis_xcorr_tag_0/axis_xcorr_tag_0_sim_netlist.v" \
"../../../../../../firmware/fpga/ad9361/ad9361_cmos_if.v" \
"../../../../../../firmware/fpga/ad9361/ad9361_dual.v" \
"../../../../../../firmware/fpga/ad9361/ad9361_dual_axis.v" \
"../../../../../../firmware/fpga/ad9361/ad9361_dual_spi.v" \
"../../../../../../firmware/fpga/ad9361/ad9361_samp_filt.v" \
"../../../../anchor_fpga.srcs/sources_1/new/anchor_clk_gen.v" \
"../../../../anchor_fpga.srcs/sources_1/new/anchor_top.v" \
"../../../../../../firmware/fpga/peak/axis_cabs_all.v" \
"../../../../../../firmware/fpga/util/axis/xilinx/axis_clk_conv_bus.v" \
"../../../../../../firmware/fpga/util/axis/axis_fan_in.v" \
"../../../../../../firmware/fpga/util/axis/axis_fan_out.v" \
"../../../../../../firmware/fpga/peak/axis_peak_all.v" \
"../../../../../../firmware/fpga/peak/axis_peak_detn.v" \
"../../../../../../firmware/fpga/mpu_if/axis_tag_data.v" \
"../../../../../../firmware/fpga/util/axis/xilinx/axis_to_mem.v" \
"../../../../../../firmware/fpga/xcorr/axis_xcorr_all.v" \
"../../../../../../firmware/fpga/util/math/counter.v" \
"../../../../../../firmware/fpga/util/filt/filt_boxcar.v" \
"../../../../../../firmware/fpga/util/math/xilinx/math_add_96.v" \
"../../../../../../firmware/fpga/util/math/math_cabs.v" \
"../../../../../../firmware/fpga/util/math/math_log2.v" \
"../../../../../../firmware/fpga/util/math/math_pow2.v" \
"../../../../../../firmware/fpga/util/misc/oh_to_bin.v" \
"../../../../../../firmware/fpga/util/misc/xilinx/shift_reg.v" \
"../../../../anchor_fpga.srcs/sim_1/new/anchor_top_tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

