# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k160tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/fzliu/orion/code/orion-anchor/projects/fpga_tag_fir/anchor_fpga.cache/wt [current_project]
set_property parent.project_path /home/fzliu/orion/code/orion-anchor/projects/fpga_tag_fir/anchor_fpga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/fzliu/orion/code/orion-anchor/projects/fpga_tag_fir/anchor_fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs /home/fzliu/orion/code/orion-anchor/firmware/fpga/include [current_fileset]
read_verilog -library xil_defaultlib {
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/ad9361/ad9361_cmos_if.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/ad9361/ad9361_dual.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/ad9361/ad9361_dual_axis.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/ad9361/ad9361_dual_spi.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/ad9361/ad9361_samp_filt.v
  /home/fzliu/orion/code/orion-anchor/projects/fpga_tag_fir/anchor_fpga.srcs/sources_1/new/anchor_clkgen.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/peak/axis_cabs_all.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/axis/xilinx/axis_clk_conv_bus.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/axis/axis_fan_in.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/axis/axis_fan_out.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/peak/axis_peak_all.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/peak/axis_peak_detn.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/xcorr/axis_xcorr_all.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/filt/filt_boxcar.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/math_cabs.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/misc/oh_to_bin.v
  /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/misc/xilinx/shift_reg.v
  /home/fzliu/orion/code/orion-anchor/projects/fpga_tag_fir/anchor_fpga.srcs/sources_1/new/anchor_top.v
}
read_ip -quiet /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/xilinx/math_sqrt_48/math_sqrt_48.xci
set_property used_in_implementation false [get_files -all /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/xilinx/math_sqrt_48/math_sqrt_48_ooc.xdc]

read_ip -quiet /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/xilinx/math_add_64/math_add_64.xci
set_property used_in_implementation false [get_files -all /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/xilinx/math_add_64/math_add_64_ooc.xdc]

read_ip -quiet /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/xilinx/math_mult_32/math_mult_32.xci
set_property used_in_implementation false [get_files -all /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/xilinx/math_mult_32/math_mult_32_ooc.xdc]

read_ip -quiet /home/fzliu/orion/code/orion-anchor/firmware/fpga/xcorr/xilinx/axis_xcorr_tag_0/axis_xcorr_tag_0.xci
set_property used_in_implementation false [get_files -all /home/fzliu/orion/code/orion-anchor/firmware/fpga/xcorr/xilinx/axis_xcorr_tag_0/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all /home/fzliu/orion/code/orion-anchor/firmware/fpga/xcorr/xilinx/axis_xcorr_tag_0/axis_xcorr_tag_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/fzliu/orion/code/orion-anchor/projects/fpga_tag_fir/anchor_fpga.srcs/constrs_1/new/anchor_fpga.xdc
set_property used_in_implementation false [get_files /home/fzliu/orion/code/orion-anchor/projects/fpga_tag_fir/anchor_fpga.srcs/constrs_1/new/anchor_fpga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top anchor_top -part xc7k160tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef anchor_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file anchor_top_utilization_synth.rpt -pb anchor_top_utilization_synth.pb"
