# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/anchor_fpga.xdc

# IP: /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/xilinx/math_sqrt_48/math_sqrt_48.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==math_sqrt_48 || ORIG_REF_NAME==math_sqrt_48} -quiet] -quiet

# IP: /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/xilinx/math_add_64/math_add_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==math_add_64 || ORIG_REF_NAME==math_add_64} -quiet] -quiet

# IP: /home/fzliu/orion/code/orion-anchor/firmware/fpga/util/math/xilinx/math_mult_32/math_mult_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==math_mult_32 || ORIG_REF_NAME==math_mult_32} -quiet] -quiet

# IP: /home/fzliu/orion/code/orion-anchor/firmware/fpga/xcorr/xilinx/axis_xcorr_tag_0/axis_xcorr_tag_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_xcorr_tag_0 || ORIG_REF_NAME==axis_xcorr_tag_0} -quiet] -quiet
